name: "Check Spelling"

on:
  push:
    branches: [ "main", "!dependabot/**" ]
  pull_request:
    branches: [ "main", "!dependabot/**" ]

permissions:
  contents: read

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive
      - uses: streetsidesoftware/cspell-action@v9
        with:
          summary: true
          incremental_files_only: false
